---
title: "the R psfmi package"
author: "Martijn W Heymans"
description: "R psfmi package for Predictor selection after Multiple Imputation in Logistic and Cox Regression models"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{psfmi}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
tags:
- psfmi
- Multiple Imputation
- backward selection
- logistic regression
- Meng and Rubin
- Rubins Rules
categories: ["psfmi"]  
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Introduction

On this page you will find information about the psfmi package. 
The	package contains functions to pool logistic (psfmi_lr) or Cox 
regression (psfmi_coxr) models in multiple imputed datasets. It is also possible to 
apply backward variable selection in multiple imputed datasets (Be aware that backward selection 
may result in overfitted and optimistic prediction models, see [TRIPOD](http://annals.org/aim/fullarticle/2088542/transparent-reporting-multivariable-prediction-model-individual-prognosis-diagnosis-tripod-explanation)). Backward selection should therefore be followed by internal validation of the model. This is also possible with the psfmi package. 

Pooling methods are Rubin's Rules, and especially of interest for categorical predictors,
the total covariance matrix (D1 method), pooling Chi-square values 
(D2 method), pooling Likelihood ratio statistics (D3 method) 
or pooling the median p-values (MPR rule). Moreover, pooling results can be obtained for
models including two-way interaction terms between continuous, dichotomous, categorical predictors
and restricted cubic spline variables. This is also allowed during variable selection. Further, 
all type of predictors, interaction terms or a combination, can be forced in the model during variable selection. 
For very large datasets and a large number of imputed datasets the D1 and MR methods may be less 
efficient than the D2 and MPR methods.

The package also contains a function to generate pooled apparent model performance 
measures as ROC/AUC, Nagelkerke R-squares, Hosmer & Lemeshow test values and calibration plots over imputed datasets (miperform_lr). A wrapper function 
over Frank Harrell's validate function is available. Bootstrap internal 
validation is performed in each imputed dataset and results are pooled. 
Backward Selection as part of internal validation	is optional and recommended.

There is also a function to perfrom external validation in multiply imputed 
datasets (mivalext_lr).  

## Installing the psfmi package

The package can be installed by running the following code in 
the R console window:
 
 install.packages("devtools")
 
 library(devtools)
 
 devtools::install_github("mwheymans/psfmi")
 
 library(psfmi)

## Main functions

The main functions that are available in the psfmi package are:

psfmi_lr: Pooling and predictor selection function for Logistic regression models in multiply imputed datasets 

psfmi_coxr: Pooling and predictor selection function for Cox regression models in multiply imputed datasets

miperform_lr: Evaluate performance of logistic regression models over multiply imputed datasets 

mivalext_lr: External Validation of logistic prediction models in multiply imputed datasets

